apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy-sts
  template:
    metadata:
      labels:
        app: swiggy-sts
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "5Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
